// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kopmwygnytijezrhzdtp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtvcG13eWdueXRpamV6cmh6ZHRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0MzkzODgsImV4cCI6MjA1OTAxNTM4OH0.zf2RoHPS1T5dYlJGldp09EMKn73UFW0KyiMuwFNAEBs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);